name: Laravel CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images
      run: docker-compose -f .docker-compose.yml-ci build --pull --no-cache
    - name: Bringup the environment
      run: docker-compose -f .docker-compose.yml-ci up -d
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '60s'
    - name: List all containers
      run: docker ps -a
    - name: Testing connection to MySQL Router
      run: docker-compose -f .docker-compose.yml-ci exec -T router mysql -Aproot -h 127.0.0.1 --port 6446 db_test -e 'select 1;'
    - name: Get InnoDB cluster status
      run: docker-compose -f .docker-compose.yml-ci exec -T mysql_node01 mysql -Aproot -h 127.0.0.1 -e 'select * from performance_schema.replication_group_members;'